version: "3.9"
services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"